---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Create ubuntu user
  user:
    name: ubuntu
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ 'ubuntu' | password_hash('sha512') }}"
    update_password: on_create

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - openssl
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker and Docker Compose
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present

# allow ubuntu to run docker commands without sudo
- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
    
- name: Create Nginx Proxy Manager directory
  file:
    path: ~/nginx-proxy-manager
    state: directory

- name: Copy docker-compose.yml for Nginx Proxy Manager
  copy:
    src: docker-compose.yml
    dest: ~/nginx-proxy-manager/docker-compose.yml

- name: Ensure Nginx Proxy Manager is running
  docker_compose:
    project_src: ~/nginx-proxy-manager
    state: present

- name: Install code-server
  shell: curl -fsSL https://code-server.dev/install.sh | sh

- name: Create systemd service file for code-server
  template:
    src: code-server.service.j2
    dest: /etc/systemd/system/code-server.service

- name: Reload systemd and start code-server service
  systemd:
    daemon_reload: yes
    name: code-server
    state: started
    enabled: yes

- name: Configure UFW firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 81
    - 443
    - 8080