version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    network_mode: "host"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
      MYSQL_DATABASE: '{{ mysql_database }}'
      MYSQL_USER: '{{ mysql_user }}'
      MYSQL_PASSWORD: '{{ mysql_password }}'
    volumes:
      - ./data/mysql:/var/lib/mysql
